{
 "title": "Repo Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "REPO",
    "label": "Repository",
    "query": {
     "query": "label_values(analysis_duration_ms_total,repo)"
    }
   },
   {
    "name": "STATUS",
    "query": {
     "query": "label_values(repo_push_total,status)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$STATUS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "STATUS" },
  {
   "title": "Push Events - $STATUS",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(repo_push_total{status=\"$STATUS\"}[1m])) by (repo) > 0",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  { "title": "Repositories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Successful Analysis",
   "type": "table",
   "gridPos": { "h": 22, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(analysis_status_total{status=\"OK\"}[$__range])) by (repo))"
    }
   ]
  },
  {
   "title": "Failed Analysis",
   "type": "table",
   "gridPos": { "h": 22, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(analysis_status_total{status=\"ERROR\"}[$__range])) by (repo))"
    }
   ]
  },
  {
   "title": "Resultless Analysis",
   "type": "table",
   "gridPos": { "h": 22, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(analysis_status_total{status=\"NONE\"}[$__range])) by (repo))"
    }
   ]
  },
  {
   "title": "Active Repositories",
   "type": "table",
   "gridPos": { "h": 22, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(repo_push_total[$__range])) by (repo))"
    }
   ]
  },
  { "title": "$REPO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }, "repeat": "REPO" },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(analysis_duration_ms_total{repo=\"$REPO\", failure=\"\"}[1m])",
     "legendFormat": "Successful Analysis Duration"
    },
    {
     "expr": "increase(analysis_duration_ms_total{repo=\"$REPO\", failure!=\"\"}[1m])",
     "legendFormat": "Failed with: {{failure}}"
    }
   ]
  }
 ]
}