apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: technolinator
  title: technolinator
  description: "GitHub app for SBOM creation using cdxgen and upload to Dependency-Track"
  annotations:
    github.com/project-slug: MediaMarktSaturn/technolinator # https://backstage.io/docs/features/software-catalog/well-known-annotations/#githubcomproject-slug
    github.com/team-slug: MediaMarktSaturn/software-supply-chain-security
    mms.tech/ref_uuid: <REF_UUID> # LeanIX refUUID
    mms.tech/product_id: '6239' # Deprecated: retained temporarily for backward compatibility with legacy tooling; remove once all consumers are migrated.
    mms.tech/app_id:  # Deprecated: retained temporarily for backward compatibility with legacy tooling; remove once all consumers are migrated.
spec:
  type: service  # alternatives: website, library
  lifecycle: production # alternative: experimental, deprecated
  owner: Cyber Security

# Errors found during processing:
#  metadata.annotations.mms.tech/ref_uuid: Does not match format 'uuid'