schemaVersion: 2.0.0

fileExistenceTests:
    - name: 'App folder exists and has the right permissions'
      path: /app
      shouldExist: true
      permissions: 'dr-xr-xr-x'
      uid: 0
      gid: 0

    - name: 'App runner jar exists and has the right permissions'
      path: /app/quarkus-run.jar
      shouldExist: true
      permissions: '-rw-r--r--'
      uid: 0
      gid: 0

    - name: 'App folder exists and has the right permissions'
      path: /app/quarkus
      shouldExist: true
      permissions: 'drwxr-xr-x'
      uid: 0
      gid: 0

    - name: 'App start script exists and has the right permissions'
      path: /app/run-java.sh
      shouldExist: true
      permissions: '-r-xr-xr-x'
      uid: 0
      gid: 0

    - name: 'Git ask pass exists with right permissions'
      path: /app/git_askpass.sh
      shouldExist: true
      permissions: '-r-xr-xr-x'
      uid: 0
      gid: 0

    - name: 'Grype template exists with right permissions'
      path: /app/grype.tmpl
      shouldExist: true
      permissions: '-r-xr-xr-x'
      uid: 0
      gid: 0

commandTests:
    - name: 'Timezone is UTC'
      command: 'date'
      args: ['+%Z']
      expectedOutput:
          - 'UTC'
    - name: "Cdxgen installed"
      command: 'cdxgen'
      args: ['-h']
      expectedOutput:
          - '.*SBoM.*'
    - name: "Grype installed"
      command: 'grype'
      args: ['-h']
      expectedOutput:
          - '.*A vulnerability scanner for container images, filesystems, and SBOMs.*'
    - name: "Sbomqs installed"
      command: 'sbomqs'
      args: ['-h']
      expectedOutput:
          - '.*SBOM Quality Score.*'
    - name: "Java installed"
      command: 'java'
      args: ["-version"]
      expectedError:
          - '.*OpenJDK Runtime Environment.*'
    - name: "Maven installed"
      command: 'mvn'
      args: ["--version"]
      expectedOutput:
          - '.*Apache Maven 3.*'
    - name: "Gradle installed"
      command: 'gradle'
      args: ["--version"]
      expectedOutput:
          - '.*Gradle 7.*'
    - name: "Git ask pass runs"
      command: '/app/git_askpass.sh'
      expectedOutput:
          - ''
    - name: "Application starts"
      command: '/app/run-java.sh'
      exitCode: 1
      expectedOutput:
          - '.*exec java --enable-preview .*'
          - '.*Missing value for configuration properties.*'
          -  '.*This configuration is required in prod mode.*'

    - name: "Composer installed"
      command: 'composer'
      args: ["about"]
      expectedOutput:
          - 'Composer - Dependency Manager for PHP.*'

    - name: "Java 17 available"
      command: '$JAVA17_HOME/bin/java'
      args: ["--version"]
      expectedOutput:
          - '.*openjdk 17.0.7.*'

    - name: "Java 20 available"
      command: '$JAVA20_HOME/bin/java'
      args: ["--version"]
      expectedOutput:
          - '.*openjdk 20.*'

    - name: "Running as non-root"
      command: 'whoami'
      expectedOutput:
          - 'app'

    - name: "Write access is prohibited"
      command: 'rm'
      args: ["-rf", "/app/run-java.sh", "/app/git_askpass.sh", "/app/quarkus-run.jar", "/etc/localtime"]
      exitCode: 1
      expectedError:
          - "rm: cannot remove '/app/run-java.sh': Permission denied"
          - "rm: cannot remove '/app/git_askpass.sh': Permission denied"
          - "rm: cannot remove '/app/quarkus-run.jar': Permission denied"
          - "rm: cannot remove '/etc/localtime': Permission denied"

metadataTest:
    labels:
        - key: 'maintainer'
          value: 'MediaMarktSaturn Technology'
    envVars:
        - key: SENSITIVE_ENV_VARS
          value: 'QUARKUS_GITHUB_APP_APP_ID,QUARKUS_GITHUB_APP_WEBHOOK_SECRET,QUARKUS_GITHUB_APP_PRIVATE_KEY,GITHUB_TOKEN,DTRACK_APIKEY'
        - key: ALLOWED_ENV_SUBSTITUTIONS
          value: ''
        - key: INTERLYNK_DISABLE_VERSION_CHECK
          value: 'true'
        - key: GRYPE_CHECK_FOR_APP_UPDATE
          value: 'false'
        - key: GIT_ASKPASS
          value: '/app/git_askpass.sh'
        - key: JAVA_HOME
          value: '/app/sdks/java/20.0.1-tem'
        - key: JAVA17_HOME
          value: '/app/sdks/java/17.0.7-tem'
        - key: JAVA20_HOME
          value: '/app/sdks/java/20.0.1-tem'
        - key: MAVEN_HOME
          value: '/app/sdks/maven/current'
        - key: GRADLE_HOME
          value: '/app/sdks/gradle/current'
        - key: MVN_CMD
          value: 'mvn'
        - key: GRADLE_CMD
          value: 'gradle'
        - key: APP_DATA
          value: '/data'
        - key: APP_DIR
          value: '/app'
        - key: GRYPE_TEMPLATE
          value: '/app/grype.tmpl'
    cmd: ['/app/run-java.sh']
    entrypoint: []
    workdir: '/data'
    user: 'app'
