schemaVersion: 2.0.0

fileExistenceTests:
    - name: 'App folder exists and has the right permissions'
      path: /app
      shouldExist: true
      permissions: 'drwxrwxr-x'
      uid: 201
      gid: 101

    - name: 'App runner jar exists'
      path: /app/quarkus-run.jar
      shouldExist: true
      uid: 201
      gid: 101

    - name: 'App start script exists and has the right permissions'
      path: /app/run-java.sh
      shouldExist: true
      permissions: '-rwxr-xr-x'
      uid: 201
      gid: 101

commandTests:
    - name: 'Timezone is UTC'
      command: 'date'
      args: ['+%Z']
      expectedOutput:
          - 'UTC'
    - name: "Cdxgen installed"
      command: 'cdxgen'
      args: ['-h']
      expectedOutput:
          - '.*SBoM.*'
    - name: "Java installed"
      command: 'java'
      args: ["-version"]
      expectedError:
          - '.*OpenJDK Runtime Environment.*'
    - name: "Maven installed"
      command: 'mvn'
      args: ["--version"]
      expectedOutput:
          - '.*Apache Maven 3.*'
    - name: "Gradle installed"
      command: 'gradle'
      args: ["--version"]
      expectedOutput:
          - '.*Gradle 7.*'
    - name: "Git ask pass runs"
      command: '/app/git_askpass.sh'
      expectedOutput:
          - ''
    - name: "Application starts"
      command: '/app/run-java.sh'
      exitCode: 1
      expectedOutput:
          - '.*exec java --enable-preview .*'
          - '.*Missing value for configuration properties.*'
          -  '.*This configuration is required in prod mode.*'

    - name: "Java 17 available"
      command: '$JAVA17_HOME/bin/java'
      args: ["--version"]
      expectedOutput:
          - '.*openjdk 17.0.6.*'

    - name: "Java 20 available"
      command: '$JAVA20_HOME/bin/java'
      args: ["--version"]
      expectedOutput:
          - '.*openjdk 20.*'

    - name: "Running as non-root"
      command: 'whoami'
      expectedOutput:
          - 'app'

metadataTest:
    labels:
        - key: 'maintainer'
          value: 'MediaMarktSaturn Technology'
    envVars:
        - key: GIT_ASKPASS
          value: '/app/git_askpass.sh'
        - key: JAVA_HOME
          value: '/app/sdks/java/20-tem'
        - key: JAVA17_HOME
          value: '/app/sdks/java/17.0.6-tem'
        - key: JAVA20_HOME
          value: '/app/sdks/java/20-tem'
        - key: MAVEN_HOME
          value: '/app/sdks/maven/current'
        - key: GRADLE_HOME
          value: '/app/sdks/gradle/current'
        - key: MVN_CMD
          value: 'mvn'
        - key: GRADLE_CMD
          value: 'gradle'
    cmd: ['/app/run-java.sh']
    entrypoint: []
    workdir: '/app'
    user: 'app'
