schemaVersion: 2.0.0

fileExistenceTests:
    - name: 'App folder exists and has the right permissions'
      path: /app
      shouldExist: true
      permissions: 'drwxrwxr-x'

    - name: 'App runner jar exists'
      path: /app/quarkus-run.jar
      shouldExist: true

    - name: 'App start script exists and has the right permissions'
      path: /app/run-java.sh
      shouldExist: true
      permissions: '-rwxr-xr-x'

    - name: 'Maven settings file should exist'
      path: /root/.m2/settings.xml
      shouldExist: true

commandTests:
    - name: 'Timezone is UTC'
      command: 'date'
      args: ['+%Z']
      expectedOutput:
          - 'UTC'
    - name: "Cdxgen installed"
      command: 'cdxgen'
      args: ['-h']
      expectedOutput:
          - '.*SBoM.*'
    - name: "Java installed"
      command: 'java'
      args: ["-version"]
      expectedError:
          - '.*OpenJDK Runtime Environment.*'
    - name: "Maven installed"
      command: 'mvn'
      args: ["--version"]
      expectedOutput:
          - '.*Apache Maven 3.*'
    - name: "Gradle installed"
      command: 'gradle'
      args: ["--version"]
      expectedOutput:
          - '.*Gradle 7.*'
    - name: "Git ask pass runs"
      command: '/root/git_askpass.sh'
      expectedOutput:
          - ''
    - name: "Application starts"
      command: '/app/run-java.sh'
      exitCode: 1
      expectedOutput:
          - '.*exec java --enable-preview .*'
          - '.*Missing value for configuration properties.*'
          -  '.*This configuration is required in prod mode.*'

metadataTest:
    labels:
        - key: 'maintainer'
          value: 'MediaMarktSaturn Technology'
    envVars:
        - key: JAVA_HOME
          value: '/usr/lib/jvm/jre'
        - key: MAVEN_HOME
          value: '/root/.sdkman/candidates/maven/current'
        - key: GRADLE_HOME
          value: '/root/.sdkman/candidates/gradle/current'
        - key: MVN_CMD
          value: 'mvn'
        - key: GRADLE_CMD
          value: 'gradle'
        - key: ARTIFACTORY_URL
          value: 'https://artifactory.cloud.mmst.eu/artifactory'
    cmd: ['/app/run-java.sh']
    entrypoint: []
    workdir: '/app'
