---
name: "Close Dependabot Pull Request"

"on":
  pull_request_target:
    types:
      - "opened"
      - "reopened"
    branches:
      - "main"
    paths:
      - "src/test/**"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: superbrothers/close-pull-request@9c18513d320d7b2c7185fb93396d0c664d5d8448 # v3.1.2
        with:
          comment: "@dependabot ignore this dependency"
