---
name: Renovate
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '23 5 * * *'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Renovate
        uses: renovatebot/github-action@248bf5a619694187930adc80b9343c37761c173f # v43.0.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
